### ISSUE TITLE
M003 - Módulo Hero

### ISSUE THREAD

**Issue by SilvanaBgn** [SilvanaBgn/static-web-page#3]
Descripción
----
Este módulo es parte de la **sección Inicio**.

Consiste en una foto de portada "Hero" de tipo .jpg (png no porque no necesito transparencia y es màs pesada)
con iconitos debajo y palabras, para identificar el rubro.

Alternativas posibles
----
Podría ser todo en una misma foto, o una imagen con iconitos+palabras arriba.

**Comment by jose-decima** [comment]
si usas la foto y el texto por aparte , luego podes editar el texto sin necesidad de cambiar la foto
